### ISSUE TITLE
Adding Iceland to analysis also adds random islands

### ISSUE THREAD

**Issue by brynpickering** [timtroendle/possibility-for-electricity-autarky#2]
This issue relates to adding Iceland for use in a downstream dependency, Euro-Calliope (see https://github.com/timtroendle/euro-calliope/issues/15).

Including Iceland here is relatively straightforward, it just requires:

1. Updating the snakemake config to include Iceland in the list of countries (inc. at every resolution), and to extend the spatial bounds to cover Iceland.
2. Updating the renewables.ninja capacity factor datasets, now that there are more points to simulate.

There's only one issue: on creating the ninja input configs I noticed that the extended spatial bounds of the problem leads to a bunch of island territories ending up in the model:

![image](https://user-images.githubusercontent.com/17178478/79363511-e6cbbb00-7f3f-11ea-849b-2c41375b5b36.png)

These same islands will end up elsewhere in the analysis, since the spatial bounds are used to set the study area in e.g. generating shapefiles. Thoughts on the easiest way to exclude these @timtroendle, or do you imagine they won't be a problem?

**Comment by timtroendle** [comment]
I think this is a problem as the demand data does not include these islands (entso-e, 2016). However, as this is the case, maybe it would be even _good_ to have a special case treatment here that removes Madeira and the Azores explicitly, not implicitly like before.

entso-e. (2016). <i>Specific national considerations</i>. https://www.entsoe.eu/Documents/Publications/Statistics/Specific_national_considerations.pdf

**Comment by brynpickering** [comment]
I wonder if we could provide the bounds of the system as a shapefile, instead of bounds of a rectangle? Or does that over-complicate the cutting down of input data (which currently uses those bounds)?

**Comment by timtroendle** [comment]
I think the code would not change much if we were to use a shapefile (basically a complex polygon I guess, no?) rather than a box. The configuration would become more complicated though. Instead of 4 values you would need a long textfile describing the polygon (assuming it is stored as a GeoJSON rather than as a shapefile).

I think I'd rather take [the current box](https://github.com/timtroendle/possibility-for-electricity-autarky/blob/c7bf64c68ab1810c42f9b42a5624ad2419920891/src/gadm.py#L34), and then stamp our Madeira and the Azores. The coordinates of the islands can be hard coded. The stamping could be controlled by one or two more flags in the config:

```yaml
scope:
    countries:
        [...]
    bounds:
        x_min: [...]
        [...]
        y_max: [...]
        include-madeira: True
        include-azores: True
```

Those are weirdly specific configuration parameters, but it looks like a pragmatic solution to me.

**Comment by brynpickering** [comment]
How about being able to define exclusion zones?

```yaml
scope:
    countries:
        [...]
    bounds:
        x_min: [...]
        [...]
        y_max: [...]
    exclusion_zones:
        atlantic_islands: 
            x_min: [...]
            [...]
            y_max: [...]
```

It could then be any arbitrary number of exclusion zones that are named by the user for convenience (`atlantic_zones` could just as easily be `random_stuff` for all the workflow cares)
